resources:
  - name: utility_repo
    type: gitRepo
    repoPath: jpline/sample-script
    configuration:
      integrationName: github
      branches:
        only: test
    initialVersion:
      sha: test

pipelines:
  - name: pipeline1
    steps:  
      - name: utility_u16
        type: bash
        configuration:
          timeoutSeconds: 360
        triggeredBy:
          resources:
            - utility_repo
        execution:
          onExecute:
            - printenv
            - bump_semver v1.0.1 major
            - bump_semver v0.0.1 patch
            - compare_git --resource utility_repo --commit-range HEAD~3..HEAD test.sh
          onComplete:
            - echo "Oh Yeah Done ubuntu 16!"
            
      - name: utility_c7
        type: bash
        configuration:
          timeoutSeconds: 360
          nodePool: kermit_centos_pool
        triggeredBy:
          resources:
            - utility_repo
        execution:
          onExecute:
            - printenv
            - bump_semver v1.0.1 major
            - bump_semver v0.0.1 patch
            - compare_git --resource utility_repo --commit-range HEAD~3..HEAD test.sh
          onComplete:
            - echo "Oh Yeah Done centOS 7!"
      
      - name: utility_u18
        type: bash
        configuration:
          timeoutSeconds: 360
          nodePool: kermit_ubuntu18
        triggeredBy:
          resources:
            - utility_repo
        execution:
          onExecute:
            - printenv
            - bump_semver v1.0.1 major
            - bump_sermer v0.0.1 patch
            - compare_git --resource utility_repo --commit-range HEAD~3..HEAD test.sh
          onComplete:
            - echo "Oh Yeah Done ubuntu 18!"
 
