resources:
  
  - name: testwebhookInternal
    type: webhook
    configuration:
      integrationName: varsha_internalWebhook
    version:
      payload: "from_resource_internal"
  
  - name: testwebhookExternal
    type: webhook
    configuration:
      integrationName: varsha_externalWebhook
    version:
      payload: "from_resource_external"
      
pipelines:
  - name: testVarsha_pipeline
    steps:  
      - name: outputWebhook
        type: bash
        requires:
          integrations:
            - varsha_internalWebhook
        execution:
          onExecute:
            - printenv
            - write_output testwebhookInternal "payload=update_from_step_for_Internalwebhook" #_resource"
          onComplete:
            - echo "Yeah, posted output resource"
        outputResources:
          - testwebhookInternal
            
      - name: triggeredBy_webhookResource
        type: bash
        triggeredBy:
          resources:
            - testwebhookInternal
         # steps:
          #  - outputWebhook
        execution:
          onExecute:
            - printenv
          onComplete:
            - echo "Oh Yeah Done!"

      - name: dep_test
        type: bash
        triggeredBy:
          steps:
            - outputWebhook
        execution:
          onExecute:
            - printenv
          onComplete:
            - echo "Oh Yeah Done!!"
        outputResources:
          - testwebhookExternal
