resources:
  - name: sample_scriptrepo
    type: gitRepo
    repoPath: jpline/sample-script
    configuration:
      integrationName: github
      branches:
        except: test_*
    initialVersion:
      sha: test
      
  - name: imageDocker
    type: image
    imageName: shippabledocker/sample-node
    configuration:
      integrationName: dockerInt
    initialVersion:
      imageTag: latest
 
pipelines:
  - name: pipeline1
    steps:  
      - name: testJob1
        type: bash
        configuration:
          timeoutSeconds: 50000 #standard max timeout seconds is 3600 seconds it is exceeding that. "0.9" and "aaa" 
        setup:
          environmentVariables:
            normal:
              ENV1: value1
              ENV3: value3
              ENV4: $ENV3
              STEP_TYPE: update #standard variable shouldnot allowed to change . a warnign or error should be shown
              PIPELINE_NAME: update
              STEP_NAME: update
         #     RUNNING_IN_CONTAINER: container #this throw error when i update this
            secure:
              ENV2: EpEMlpUSs85U6Y5WmsV5xXUr/GkDpuKP0qH6yy4qPoTbZUSRwmIwWhez+bNSmDJe7lkZN1+syxU1LFmt09QqtSVQpy69brIW1L6vLaHVtBn7hcYGC3dJhmvXUYn/ohpasFj/sab6lwXHQSs+nRYyFRF+ICRzoTB6M17JW/KoLpqJrLL1hBYC1gPSXuWgJT/ZqKWcg+GWhCZT1o9L6IrHrgaMYR3aSmWwGAZoUBWGuTw7/datT6NDhxD6nX64dRdcR+4X0yRnTLPzbxqiMC9qTBw4ChIw5CenyH0tE/AF6YlhoavkyyRBkgd18AQKVNpQneaRN7htnIe+fLEsbKEkwQ==
        triggeredBy:
          resources:
            - sample_scriptrepo
            - test #should throw error doesnot exist
          integrations:
            - dockerInt #shouldnot allow integrations in triggered by
        requires:
          integrations:
            - dockerInt
        runtime:            
          type: host #should throw error i have mentioned host and added image
          image:
            custom:
              name: drydock/u16all
              tag: v7.2.4
              options: 'privileged: true'
          type: image #should throw error i have already mentioned as host
          image:
            custom:
              name: drydock/u16all
              tag: v7.2.4
              options: 'privileged: true'
           
        execution:
          onExecute:
            - printenv
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            - echo "ENV3=$ENV3"
            - echo "ENV4=$ENV4"
            - echo "STEP_TYPE=$STEP_TYPE"
            - echo "PIPELINE_NAME=$PIPELINE_NAME"
            - echo "STEP_NAME=$STEP_NAME"
          #  - echo "RUNNING_IN_CONTAINER=$RUNNING_IN_CONTAINER"
          onExecute:
            - echo "duplicate on execute should fail" #onexecute 2 times should throw error
            
      - name: testJob1
        type: bash
        triggeredBy:
          resources:
            - imageDocker
        setup:
          environmentVariables:
            normal:
              ENV1: "'value1 value2 ... valuen'"
              ENV2: "value2 value3 value4"
        execution:
          onExecute:
            - printenv
            - echo "ENV1=$ENV1"
            - echo "ENV2=$ENV2"
            

       
  - name: pipeline2
    steps:    
      - name: testJob1
        type: bash
        execution:
          onExecute:
            - printenv
  

       
