resources:
  - name: sampleScript_ap
    type: gitRepo
    repoPath: jpline/sample-script
    configuration:
      integrationName: varsha_github
      branches:
        only: master*
    version:
      sha: master
  
  - name: file_ap
    type: file
    configuration:
      integrationName: varsha_artifactory
    version:
      pattern: "npm-dev-local/"

  - name: buildInfo_ap
    type: buildInfo
    version:
      buildName: $PIPELINE_NAME
      buildNumber: 1 # will be updated to $RUN_NUMBER after we have OUT in publish_ap step
     # targetRepo: test
      
  - name: promoteInfo_ap
    type: buildInfo
    version:
      buildName: promote_bldinfo
      buildNumber: 1  
      
pipelines:
  - name: VarshaTestPipeline
    steps:  
      - name: bash_ap
        type: bash
        requires:
          integrations:
            - notifySlack
        execution:
          onExecute:
            - printenv
            - send_notification 
          onComplete:
            - echo "Oh Yeah Done affinity group"

      - name: build_ap
        type: build
        payloadType: docker
        setup:
          build:
            dockerFileLocation: .
            dockerFileName: Dockerfile
            imageName: 34.66.110.173:8081/docker-local/ankul
            imageTag: $PIPELINE_NAME.$RUN_NUMBER
        triggeredBy:
          steps:
            - bash_ap
        requires:
          integrations:
            - varsha_artifactory
          resources:
            - sampleScript_ap
            - file_ap

      - name: push_ap
        type: push
        setup:
          push:
            targetRepo: docker-local
        requires:
          integrations:
            - varsha_artifactory
        triggeredBy:
          steps:
            - build_ap
            
      - name: publish_ap
        type: publish
        requires:
          integrations:
            - varsha_artifactory
        triggeredBy:
          steps:
            - push_ap
        outputResources:
          - buildInfo_ap
      
      - name: promote_ap
        type: promote
        setup:
          promote:
            targetRepo: ankul_local_repo    
        requires:
          integrations:
            - varsha_artifactory         
        triggeredBy:
          resources:
            - buildInfo_ap
        outputResources:
          - promoteInfo_ap     
