resources:
  - name: sample_scriptrepo
    type: gitRepo
    repoPath: jpline/sample-script
    configuration:
      integrationName: varsha_github
      branches:
        only: test
    initialVersion:
      sha: test

pipelines:
  - name: pipeline1
    steps:  
      - name: utility_u16
        type: bash
        configuration:
          timeoutSeconds: 360
        triggeredBy:
          resources:
            - sample_scriptrepo
        execution:
          onExecute:
            - printenv
            - bump_semver v1.0.1 major
            - bump_semver v0.0.1 patch
          onComplete:
            - echo "Oh Yeah Done ubuntu 16!"
            
      - name: utility_c7
        type: bash
        configuration:
          timeoutSeconds: 360
          nodePool: kermit_centos_pool
        triggeredBy:
          resources:
            - sample_scriptrepo
        execution:
          onExecute:
            - printenv
            - bump_semver v1.0.1 major
            - bump_semver v0.0.1 patch
          onComplete:
            - echo "Oh Yeah Done centOS 7!"
      
      - name: utility_u18
        type: bash
        configuration:
          timeoutSeconds: 360
          nodePool: kermit_ubuntu18
        triggeredBy:
          resources:
            - sample_scriptrepo
        execution:
          onExecute:
            - printenv
            - bump_semver v1.0.1 major
            - bump_sermer v0.0.1 patch
          onComplete:
            - echo "Oh Yeah Done ubuntu 18!"
