resources:
  - name: utility_repo
    type: gitRepo
    repoPath: jpline/sample-script
    configuration:
      integrationName: varsha_github
      branches:
        only: test
    initialVersion:
      sha: test

  - name: state_reso
    type: state
    
pipelines:
  - name: Varsha_pipeline
    steps:  
      - name: utility_u16
        type: bash
        configuration:
          timeoutSeconds: 360
        triggeredBy:
          resources:
            - utility_repo
        requires:
          resources:
            - state_reso
          integrations:
            - notifySlack
            - varshaJira
        execution:
          onExecute:
            - docker pull drydock/u16node:master
            - add_run_variable imageTag="firstTest"
            
            - pushd $res_utility_repo_resourcePath
            
            - save_run_state test.sh my_file
            - restore_run_state my_file test.sh
            
            - save_resource_state state_reso echo.sh my_file
            - restore_resource_state state_reso my_file echo.sh
            - popd
            
            - printenv
            - bump_semver v1.0.1 major
            - bump_semver v0.0.1 patch
            
            - compare_git --resource utility_repo --commit-range HEAD~3..HEAD test.sh
            
            - update_commit_status utility_repo --status processing --message "updated in utility step" --context $STEP_NAME
            
            - switch_env nodejs 8.16.0
            
            - pushd $res_utility_repo_resourcePath
            - ls -la
            - read_json keys.json "DOCKER_USERNAME"
            
            - openssl genrsa -out key.pem 1024 
            - openssl rsa -in key.pem -text -noout
            - openssl rsa -in key.pem -pubout -out pub.pem 
            - openssl rsa -in pub.pem -pubin -text -noout 
            
            - encrypt_string "secretValue" --key pub.pem
            - encrypted=$(encrypt_string "secretValue" --key pub.pem)
            - echo "$encrypted"
            - decrypt_string "$encrypted" --key key.pem
            
            - encrypt_file --output encrypted.txt crypt.txt --key pub.pem
            - cat encrypted.txt
            - decrypt_file encrypted.txt --output decrypted.txt --key key.pem
            - cat decrypted.txt
            
            - replace_envs example.env sample.env
            
            - cat sample.env
            - cat example.env
  
            - cache_files echo.sh my_file
            - restore_cache my_file echo.sh
            
            - popd
            - send_notification notifySlack
            - send_notification varshaJira --project-id TES --type test --summary "no issue" --description "testing api"
             # - write_output imagePython "imageTag=master" "sha=$res_utility_repo_commitSha"
            - execute_command echo $res_utility_repo_resourcePath
          #  - retry_command "git clone git@bitbucket.org:shiptest-rc-me/testprivate.git" #worked
            - replicate_resource imageDocker imagePython #throws error
          onComplete:
            - echo "Oh Yeah Done ubuntu 16!"
            
      - name: utility_c7
        type: bash
        configuration:
          timeoutSeconds: 360
          nodePool: kermit_centos_pool
        triggeredBy:
          resources:
            - utility_repo
        requires:
          resources:
            - state_reso
          steps:
            - utility_u16
          integrations:
            - notifySlack
        execution:
          onExecute:
            - printenv
            - docker pull drydock/c7node:master
            - add_run_variable imageTag="firstTest"
            
            - pushd $res_utility_repo_resourcePath
            
            - save_run_state test.sh my_file
            - restore_run_state my_file test.sh
            
            - save_resource_state state_reso echo.sh my_file
            - restore_resource_state state_reso my_file echo.sh
            - popd
            
            - bump_semver v1.0.1 major
            - bump_semver v0.0.1 patch
            
            - compare_git --resource utility_repo --commit-range HEAD~3..HEAD test.sh
            
            - update_commit_status utility_repo --status processing --message "updated in utility step" --context $STEP_NAME
            
            - switch_env nodejs 8.16.0
            
            - pushd $res_utility_repo_resourcePath
            
            - read_json keys.json "DOCKER_USERNAME"
            - openssl genrsa -out key.pem 1024 
            - openssl rsa -in key.pem -text -noout
            - openssl rsa -in key.pem -pubout -out pub.pem 
            - openssl rsa -in pub.pem -pubin -text -noout 
            
            - encrypt_string "secretValue" --key pub.pem
            - encrypted=$(encrypt_string "secretValue" --key pub.pem)
            - echo "$encrypted"
            - decrypt_string "$encrypted" --key key.pem
            
            - encrypt_file --output encrypted.txt crypt.txt --key pub.pem
            - cat encrypted.txt
            - decrypt_file encrypted.txt --output decrypted.txt --key key.pem
            - cat decrypted.txt
            - replace_envs example.env sample.env
            
            - cat sample.env
            - cat example.env
  
            - cache_files echo.sh my_file
            - restore_cache my_file echo.sh
            
            - popd
            
            - send_notification notifySlack
            
            - execute_command echo $res_utility_repo_resourcePath
          onComplete:
            - echo "Oh Yeah Done centOS 7!"
      
      - name: utility_u18
        type: bash
        configuration:
          timeoutSeconds: 360
          nodePool: kermit_ubuntu18
        requires:
          resources:
            - state_reso
          integrations:
            - notifySlack
        triggeredBy:
          resources:
            - utility_repo
          steps:
            - utility_u16
        execution:
          onExecute:
            - printenv
            - docker pull drydock/u16node:master
            - add_run_variable imageTag="firstTest"
            
            - pushd $res_utility_repo_resourcePath
            
            - save_run_state test.sh my_file
            - restore_run_state my_file test.sh
            
            - save_resource_state state_reso echo.sh my_file
            - restore_resource_state state_reso my_file echo.sh
            - popd
            
            - bump_semver v1.0.1 major
            - bump_semver v0.0.1 patch
            
            - compare_git --resource utility_repo --commit-range HEAD~3..HEAD test.sh
            
            - update_commit_status utility_repo --status processing --message "updated in utility step" --context $STEP_NAME
            
            - switch_env nodejs 8.16.0
            
            - pushd $res_utility_repo_resourcePath
            
            - read_json keys.json "DOCKER_USERNAME"
            
            - openssl genrsa -out key.pem 1024 
            - openssl rsa -in key.pem -text -noout
            - openssl rsa -in key.pem -pubout -out pub.pem 
            - openssl rsa -in pub.pem -pubin -text -noout 
            
            - encrypt_string "secretValue" --key pub.pem
            - encrypted=$(encrypt_string "secretValue" --key pub.pem)
            - echo "$encrypted"
            - decrypt_string "$encrypted" --key key.pem
            
            - encrypt_file --output encrypted.txt crypt.txt --key pub.pem
            - cat encrypted.txt
            - decrypt_file encrypted.txt --output decrypted.txt --key key.pem
            - cat decrypted.txt
            
            - replace_envs example.env sample.env
            
            - cat sample.env
            - cat example.env
  
            - cache_files echo.sh my_file
            - restore_cache my_file echo.sh
            
            - popd
            
            - send_notification notifySlack
            
            - execute_command echo $res_utility_repo_resourcePath
          onComplete:
            - echo "Oh Yeah Done ubuntu 18!"
 
