resources:
  - name: utility_repo
    type: gitRepo
    repoPath: jpline/sample-script
    configuration:
      integrationName: varsha_github
      branches:
        only: test
    initialVersion:
      sha: test
  
  - name: webhookInt
    type: webhook
    configuration:
      integrationName: varsha_internalWebhook
    initialVersion:
      payload: "sample_one_update"
      
  - name: webhookIntExternal
    type: webhook
    configuration:
      integrationName: varsha_externalWebhook
    initialVersion:
      payload: "data=test_update"
      
pipelines:
  - name: Varsha_pipeline
    steps:  
      - name: utility_u16
        type: bash
        triggeredBy:
          resources:
            - utility_repo
          integrations:
            - varsha_internalWebhook
        execution:
          onExecute:
            - write_output webhookInt "payload=updating_outputResource_from_step_for_Internalwebhook"
          onComplete:
            - echo "Oh Yeah Done ubuntu 16"
        outputResources:
          - webhookInt
            
      - name: utility_c7
        type: bash
        triggeredBy:
          resources:
            - utility_repo
            - webhookInt
        execution:
          onExecute:
            - printenv
          onComplete:
            - echo "Oh Yeah Done centOS 7"
      
      - name: utility_u18
        type: bash
        triggeredBy:
          steps:
            - utility_u16
          resources:
            - utility_repo
        execution:
          onExecute:
            - printenv
            - write_output webhookIntExternal "payload=updating_from_step"
          onComplete:
            - echo "Oh Yeah Done ubuntu 18!"
        outputResources:
          - webhookIntExternal
